### ISSUE TITLE
Missing AAMP hash strings

### ISSUE THREAD

**Issue by ArchLeaders** [NCF-Library/AampLibrary#1]
### (Duplicate of [#9](https://github.com/ArchLeaders/NCF-Library/issues/9) from the [original repo](https://github.com/ArchLeaders/NCF-Library))

@GingerAvalanche noticed a few known hash strings that were missing from the AAMP hash list.

```yml
lists: 
  ModelData: !list
    objects: {}
    lists: 
      84677491: !list # ModelData_0
        objects: 
          Base: !obj
            Folder: !str64 Armor_001
        lists: 
          Unit: !list
            objects: 
              3316644089: !obj # Unit_0
                UnitName: !str64 Armor_001_Head_A
                BindBone: !str64 ''
            lists: {}
  AnmTarget: !list
    objects: {}
    lists: 
      3421253251: !list # AnmTarget_0
        objects: 
          Base: !obj
            NumASSlot: 3
            IsParticalEnable: True
            TargetType: 0
        lists: {}
```

---

***GingerAvalanche - Oct 4, 2022**:*

> A few that are missing from bphysics files:
> `ParamSetHeader`
> `RigidBodySetHeader`
> `CharacterControllerParam`
> `FormHeader`
> `RigidContactInfoHeader`
> `ClothHeader`
> 
> Will make a commit once I've catalogued as many of them as I can
